
export const SHOW_LOGIN_PAGE = "SHOW_LOGIN_PAGE"
export const SHOW_SIGNUP_PAGE = "SHOW_SIGNUP_PAGE"

export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAILURE = "ADMIN_SIGNUP_FAILURE"
export const ADMIN_SIGNUP_REQUEST = "ADMIN_SIGNUP_REQUEST"

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE"